const dummyColleges = [
    {
      id: 1,
      name: "IIT Madras - Indian Institute of Technology Madras[IITM] , Chennai",
      location: "Chennai",
      fees: 242000,
      placement: 2184000,
      userReviews: 9.3,
      ranking: 3,
      featured: false,
    },
    {
      id: 2,
      name: "IIT Delhi - Indian Institute of Technology[IITD] , New Delhi",
      location: "New Delhi",
      fees: 254650,
      placement: 2582000,
      userReviews: 9.7,
      ranking: 1,
      featured: false,
    },
    {
      id: 3,
      name: "IIM Bangalore - Indian Institute of Management Bangalore , Bangalore ",
      location: "Vadodara",
      fees: 2450000,
      placement: 3592000,
      userReviews: 9.1,
      ranking: 99,
      featured: true,
    },
    {
      id: 4,
      name: "IIT Bombay - Indian Institute of Technology[IITB] , Mumbai ",
      location: "Mumbai",
      fees: 229300,
      placement: 2182000,
      userReviews: 8.8,
      ranking: 2,
      featured: false,
    },
    {
      id: 5,
      name: "IIMC - Indian Institute of Management, Kolkata ",
      location: "Chennai",
      fees: 209550,
      placement: 2184000,
      userReviews: 8.6,
      ranking: 3,
      featured: false,
    },
    {
      id: 6,
      name: "IIMA - Indian Institute of Management , Ahemdabad",
      location: "New Delhi",
      fees: 2500000,
      placement: 3436000,
      userReviews: 8.7,
      ranking: 1,
      featured: false,
    },
    {
      id: 7,
      name: "FMS Delhi Faculty of Management Studies, New Delhi",
      location: "Vadodara",
      fees: 100000,
      placement: 3410000,
      userReviews: 8.1,
      ranking: 99,
      featured: true,
    },
    {
      id: 8,
      name: "SP Jain [SP JIMR], Mumbai",
      location: "Mumbai",
      fees: 2250000,
      placement: 3300000,
      userReviews: 8.8,
      ranking: 2,
      featured: false,
    },
    {
      id: 9,
      name: "IIT kharagpur - Indian Institute of Technology - [IITKGP], Kharagpur",
      location: "Chennai",
      fees: 27650,
      placement: 26000000,
      userReviews: 8.6,
      ranking: 3,
      featured: false,
    },
    {
      id: 10,
      name: "IIML - Indian Institute of Management, Lucknow",
      location: "New Delhi",
      fees: 1430000,
      placement: 3000000,
      userReviews: 8.7,
      ranking: 1,
      featured: false,
    },
    {
      id: 11,
      name: "IIT Kanpur",
      location: "Vadodara",
      fees: 220970,
      placement: 19000000,
      userReviews: 8.1,
      ranking: 99,
      featured: true,
    },
    {
      id: 12,
      name: "IIMI - Indian Institute of Management, Indore",
      location: "Mumbai",
      fees: 229300,
      placement: 2182000,
      userReviews: 8.8,
      ranking: 2,
      featured: false,
    },
    {
      id: 13,
      name: "IIMK - Indian Institute of Management, Kozhikode",
      location: "Chennai",
      fees: 1470000,
      placement: 2923000,
      userReviews: 4.3,
      ranking: 3,
      featured: false,
    },
    {
      id: 14,
      name: "IIT Roorkee - Indian Institute of Technology - [IITR], Roorkee",
      location: "New Delhi",
      fees: 230100,
      placement: 1834000,
      userReviews: 5.3,
      ranking: 1,
      featured: false,
    },
    {
      id: 15,
      name: "JBIMS Mumbai, Mumbai",
      location: "Vadodara",
      fees: 350000,
      placement: 2802000,
      userReviews: 4.1,
      ranking: 99,
      featured: true,
    },
    {
      id: 16,
      name: "IIFT Delhi Indian Institute of Foreign Trade, New Delhi",
      location: "Mumbai",
      fees: 3377314,
      placement: 2910000,
      userReviews: 6.8,
      ranking: 2,
      featured: false,
    },
    {
      id: 17,
      name: "BITS Pilani (Pilani Campus)",
      location: "Chennai",
      fees: 603775,
      placement: 3037000,
      userReviews: 6.6,
      ranking: 3,
      featured: false,
    },
    {
      id: 18,
      name: "MDI Gurgaon, Gurgaon",
      location: "New Delhi",
      fees: 41800,
      placement: 2550000,
      userReviews: 8.7,
      ranking: 1,
      featured: false,
    },
    {
      id: 19,
      name: "IIT Guwhati - Indian Institute of Technology - [IITG], Guwhati",
      location: "Vadodara",
      fees: 98250,
      placement: 24000000,
      userReviews: 9.1,
      ranking: 99,
      featured: true,
    },
    {
      id: 20,
      name: "IIM Shilong Indian Institute of Management, Shilong",
      location: "Mumbai",
      fees: 2618000,
      placement: 2696000,
      userReviews: 3.8,
      ranking: 2,
      featured: false,
    },
    {
      id: 21,
      name: "IIM Mumbai - Indian Institute of Management, Mumbai",
      location: "Chennai",
      fees: 1032000,
      placement: 5400000,
      userReviews: 6.6,
      ranking: 3,
      featured: false,
    },
    {
      id: 22,
      name: "TISS Tata Institute of Social Science, Mumbai",
      location: "New Delhi",
      fees: 388500,
      placement: 2722000,
      userReviews: 5.7,
      ranking: 1,
      featured: false,
    },
    {
      id: 23,
      name: "Department of Management Studies, IIT Madras, Chennai",
      location: "Vadodara",
      fees: 15650,
      placement: 2737272,
      userReviews: 2.1,
      ranking: 99,
      featured: true,
    },
    {
      id: 24,
      name: "Shailesh J. Mehta School of Management, IIT Bombay",
      location: "Mumbai",
      fees: 717650,
      placement: 2801000,
      userReviews: 4.8,
      ranking: 2,
      featured: false,
    },
    {
      id: 25,
      name: "DMS - Department of Management Studies IIT, New Delhi",
      location: "Chennai",
      fees: 41650,
      placement: 2582000,
      userReviews: 6.3,
      ranking: 3,
      featured: false,
    },
    {
      id: 26,
      name: "Symboisis Institute of Business Management- [SIBM], Pune",
      location: "New Delhi",
      fees: 356500,
      placement: 2816000,
      userReviews: 8.7,
      ranking: 1,
      featured: false,
    },
    {
      id: 27,
      name: "All India Institute of Medical Sciences - [AIIMS], New Delhi",
      location: "Vadodara",
      fees: 2450000,
      placement: 3592000,
      userReviews: 8.1,
      ranking: 99,
      featured: true,
    },
    {
      id: 28,
      name: "ISB Hyderabad Indian School of Business, Hyderabad",
      location: "Mumbai",
      fees: 3926000,
      placement: 3325000,
      userReviews: 3.8,
      ranking: 2,
      featured: false,
    },
    {
      id: 29,
      name: "School of Business Management, NMIMS",
      location: "Chennai",
      fees: 103000,
      placement: 2663000,
      userReviews: 5.6,
      ranking: 3,
      featured: false,
    },
    {
      id: 30,
      name: "Indian Institute of Management - [IIMU], Udaipur",
      location: "New Delhi",
      fees: 2275000,
      placement: 1880000,
      userReviews: 8.7,
      ranking: 1,
      featured: false,
    },
    {
      id: 31,
      name: "IIM Raipur - Indian Institute of Management, Raipur",
      location: "Vadodara",
      fees: 1495000,
      placement: 1907000,
      userReviews: 8.1,
      ranking: 99,
      featured: true,
    },
    {
      id: 32,
      name: "Indian Institute of Management - [IIMT], Tiruchirapalli",
      location: "Mumbai",
      fees: 1950000,
      placement: 1943000,
      userReviews: 8.8,
      ranking: 2,
      featured: false,
    },
    {
      id: 33,
      name: "Symboisis Centre for Management and Human Resource Development, Pune",
      location: "Chennai",
      fees: 1214000,
      placement: 2428000,
      userReviews: 6.6,
      ranking: 3,
      featured: false,
    },
    {
      id: 34,
      name: "IIM Ranchi - Indian Institute of Management, Ranchi",
      location: "New Delhi",
      fees: 1720000,
      placement: 1869000,
      userReviews: 8.7,
      ranking: 1,
      featured: false,
    },
    {
      id: 35,
      name: "VGSOM - Vinod Gupta School of Management IIT, Kharagpur",
      location: "Vadodara",
      fees: 619900,
      placement: 2083000,
      userReviews: 7.1,
      ranking: 99,
      featured: true,
    },
    {
      id: 36,
      name: "IIM Rohtak Indian Institute of Management, Rohtak",
      location: "Mumbai",
      fees: 786000,
      placement: 1927000,
      userReviews: 9.5,
      ranking: 2,
      featured: false,
    },
    {
      id: 37,
      name: "Indian Institute of Management - [IIM], Kashipur",
      location: "Chennai",
      fees: 1730000,
      placement: 1811000,
      userReviews: 8.6,
      ranking: 3,
      featured: false,
    },
    {
      id: 38,
      name: "IMT - Institute of Management Technology, Ghaziabad",
      location: "New Delhi",
      fees: 1003000,
      placement: 1735000,
      userReviews: 8.7,
      ranking: 1,
      featured: false,
    },
    {
      id: 39,
      name: "XIMB, Bhubaneswar",
      location: "Vadodara",
      fees: 2150000,
      placement: 1953000,
      userReviews: 8.1,
      ranking: 99,
      featured: true,
    },
    {
      id: 40,
      name: "Indian Institute of Management - [IIMN], Nagpur",
      location: "Mumbai",
      fees: 1890000,
      placement: 1630000,
      userReviews: 8.8,
      ranking: 2,
      featured: false,
    },
   
  ];
  
  export { dummyColleges };
  